todolist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.DoTitleView.as_view(), name='home'),
    path('todolist/<int:pk>', views.DoTitleDetail.as_view(), name ='detail'),
]

todolist_v2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todolist.urls')),
]

todolist/models.py
from django.db import models
from django.utils import timezone

class DoTitle(models.Model):
    api_id = models.IntegerField(default=1)
    title = models.CharField(max_length=100)
    body = models.TextField()
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

class DoComment(models.Model):
    title = models.ForeignKey(DoTitle, related_name='docomment', on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)

    def __str__(self):
        return self.comment

todolist/views.py
import json
from urllib.request import urlopen

from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView,DetailView,FormView

from .models import DoTitle,DoComment

# home 화면 #

def get_api():
    dotitle_api_url = "http://127.0.0.1:8000/dotitle/"

    dotitle_source = urlopen(dotitle_api_url)

    dotitle_jsons = json.load(dotitle_source)

    DoTitle.objects.all().delete()

    for do in dotitle_jsons:
        dotitle = DoTitle(api_id = do['id'] , title = do['title'], body = do['body'], pub_date = do['pub_date'])
        dotitle.save()
        for cmt in do['docomment']:
            com = DoComment(title= dotitle, comment=cmt['comment'])
            com.save()

        print(do)


class DoTitleView(TemplateView):
    template_name = 'todolist/home.html'

    def get_context_data(self, **kwargs):
        print("@@ get_context_data @@")
        get_api()
        context = super().get_context_data(**kwargs)
        context['dotitles'] = DoTitle.objects.all()
        return context

class DoTitleDetail(DetailView):
    model = DoTitle
    template_name = 'todolist/detail.html'
    context_object_name = "dotitle"

todolist/templates/todolist/detail.html
<h1>{{dotitle.title}}</h1>
<br>
<h3>{{dotitle.body}}</h3>
<br>
<p>{{dotitle.pub_date}}</p>
<br>
<p>{{dotitle.count}}</p>
<p>{{object.docomment_set.all}}</p>

todolist/templates/todolist/home.html
{% extends 'base.html' %}

{% block context %}
<head>

</head>

<body>
    <h1> ToDo List </h1>
    <br>
    <br>

    {%for dotitle in dotitles %}
    <div class="box-body">

        <ul class="todo-list ui-sortable">
            <li>
                <span class="handle ui-sortable-handle">
                    <i class="fa fa-ellipsis-v"></i>
                    <i class="fa fa-ellipsis-v"></i>
                </span>
                <span class="text"><a href = "{% url 'detail' dotitle.id %}" >{{dotitle.title}}</a></span>
                <small class="label label-danger"><i class="fa fa-clock-o"></i> {{dotitle.pub_date}}</small>
                <div class="tools">
                    {#<a href = "{% url 'update' todolist.id %}"><i class="fa fa-edit"></i></a> #}
                    {#<a href = "{% url 'delete' todolist.id %}"><i class="fa fa-trash-o"></i></a>#}
                </div>
            </li>
        </ul>
    </div>
    {% endfor %}
</body>

{% endblock %}

todolist_v2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from https://bootdey.com  -->
    <!--  All snippets are MIT license https://bootdey.com/license -->
    <title>택시짱의 todolist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

    <style type="text/css">
    	body{
    margin-top:20px;
    background:#eee;
}
.box.box-aqua {
    border-top-color: #00c0ef !important;
}
.box.box-green {
    border-top-color: #00a65a !important;
}
.box.box-success {
    border-top-color: #3c8dbc;
}
.box {
    position: relative;
    border-radius: 3px;
    background: #ffffff;
    border-top: 3px solid #d2d6de;
    margin-bottom: 20px;
    width: 100%;
    box-shadow: 0 1px 1px rgba(0,0,0,0.1);
}
.box-header {
    color: #444;
    display: block;
    padding: 10px;
    position: relative;
}
.box-header>.ion {
    margin-right: 5px;
}
.box-header .box-title {
    display: inline-block;
    font-size: 18px;
    margin: 0;
    line-height: 1;
}
.box-header>.box-tools {
    position: absolute;
    right: 10px;
    top: 5px;
}
.inline {
    display: inline;
}
.box-body {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 3px;
    border-bottom-left-radius: 3px;
    padding: 10px;
}
.todo-list {
    margin: 0;
    padding: 0;
    list-style: none;
    overflow: auto;
}
.todo-list>li {
    border-radius: 2px;
    padding: 10px;
    background: #f4f4f4;
    margin-bottom: 2px;
    border-left: 2px solid #e6e7e8;
    color: #444;
}
.todo-list>li .label {
    margin-left: 10px;
    font-size: 9px;
}
.todo-list>li .tools {
    display: none;
    float: right;
    color: #dd4b39;
}
.todo-list>li:hover .tools{
    display: block;
}
.no-border {
    border: 0 !important;
}
.box-footer {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 3px;
    border-bottom-left-radius: 3px;
    border-top: 1px solid #f4f4f4;
    padding: 10px;
    background-color: #fff;
}
.btn-default {
    background-color: #f4f4f4;
    color: #444;
    border-color: #ddd;
}
.btn {
    border-radius: 3px;
    -webkit-box-shadow: none;
    box-shadow: none;
    border: 1px solid transparent;
}
    </style>
</head>
<body>
<div class="row">
  <div class="col-md-6">
    <div class="box box-aqua">
      <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">To Do List</h3>
      </div>
      <div class="box-footer clearfix no-border">
          <button type="button" onclick="{#location.href='{% url 'insert' %}#}'" class="btn btn-default pull-right" ><i class="fa fa-plus"></i> 글 쓰기</button>
      </div>
      {% block context %}
      {% endblock %}


    </div>
  </div>
</div>

<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript">

</script>
</body>
</html>